lp/urls.py
from django.urls import path
from lp import views


urlpatterns = [
    path('edition/', views.edition),
    path('sample/', views.sample),
    path('meta.json', views.meta_json),
    path('icon.png', views.icon),
]

theatricalia/urls.py
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, register_converter

from . import views

from profiles import views as profiles
from plays import views as plays
from productions import views as productions
from people import views as people
from places import views as places
from search import views as search
from photos import views as photos
from common import views as common
from merged import views as merged
from news import views as news

from theatricalia import admin
from django.contrib.auth import views as auth_views

from feeds import PersonFeed, PlayFeed, PlaceFeed, NearbyFeed, UserSeenFeed, NewsFeed


class StringConverter:
    def to_python(self, value):
        return value

    def to_url(self, value):
        return value


class Base32Converter(StringConverter):
    regex = '[0-9a-zA-Z]+'


class LetterConverter(StringConverter):
    regex = '[a-z0*]'


class EmptySlugConverter(StringConverter):
    regex = '[-a-zA-Z0-9_]*'


register_converter(Base32Converter, 'b32')
register_converter(LetterConverter, 'letter')
register_converter(EmptySlugConverter, 'emptyslug')

urlpatterns = [
    # Example:
    # (r'^theatricalia/', include('theatricalia.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    path('admin/', admin.site.urls),

    path('tickets/boxoffice', profiles.register, name='register'),
    path('tickets/<b32:uidb32>-<path:token>', profiles.register_confirm, name='register-confirm'),
    path('tickets', profiles.LoginView.as_view(), name='login'),
    path('tickets/exchange', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('tickets/exchanged', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('tickets/lost', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('tickets/lost/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('tickets/lost/<slug:uidb64>/<path:token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('tickets/lost/found', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('tickets/returns', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.home, name='home'),

    path('about', views.static_about, name='about'),
    path('assistance', views.static_help, name='help'),
    path('flag', views.static_flag, name='flag'),
    path('criticism', views.static_contact, name='criticism'),
    path('colophon', views.static_colophon, name='colophon'),
    path('moo', views.static_moocards, name='moo'),

    path('play/<b32:id>/<slug:slug>/feed', PlayFeed()),
    path('person/<b32:id>/<slug:slug>/feed', PersonFeed()),
    path('place/<b32:id>/<slug:slug>/feed', PlaceFeed()),
    path('around/<slug:coord>/feed', NearbyFeed()),
    path('profile/<slug:user>/feed/seen', UserSeenFeed()),

    path('play/<b32:play_id>/<slug:play>/production/<b32:id>/merge', merged.production_merge),
    path('<type>/<b32:id>/<slug:slug>/merge', merged.merge),
    path('<type>/<b32:id>/merge', merged.merge),
    path('merge/<b32:uidb32>/<path:token>/<type>', merged.approve, name='merge_approve'),

    path('d/<b32:production_id>', productions.production_short_url),
    path('production/<b32:production_id>', productions.production_short_url),
    path('c/<b32:company_id>', productions.production_company_short_url),
    path('p/<b32:play_id>', plays.play_short_url),
    path('t/<b32:place_id>', places.place_short_url),
    path('a/<b32:person_id>', people.person_short_url),

    path('api/<type>/<b32:id>/flickr', common.api_flickr),

    path('plays', plays.PlayList.as_view(), name='plays_all'),
    path('plays/<letter:letter>', plays.PlayList.as_view(), name='plays'),
    path('play/<b32:play_id>/<slug:play>/production/<b32:production_id>/seen/<type>', productions.production_seen, name='production-seen'),
    path('play/<b32:play_id>/<slug:play>/production/<b32:production_id>/edit', productions.production_edit, name='production-edit'),
    path('play/<b32:play_id>/<slug:play>/production/<b32:production_id>/edit/cast', productions.production_edit_cast, name='production-edit-cast'),
    path('play/<b32:play_id>/<slug:play>/production/<b32:production_id>/edit/<int:part_id>', productions.part_edit, name='part-edit'),
    path('play/<b32:play_id>/<slug:play>/production/<b32:production_id>/corrected', productions.production_corrected, name='production-corrected'),
    path('play/<b32:play_id>/<slug:play>/production/<b32:production_id>.json', productions.production, {'format': 'json'}, name='production-json'),
    path('play/<b32:play_id>/<slug:play>/production/<b32:production_id>', productions.production, name='production'),
    path('play/<b32:play_id>/<slug:play>/future', plays.play_productions, {'type': 'future'}, name='play-productions-future'),
    path('play/<b32:play_id>/<slug:play>/past', plays.play_productions, {'type': 'past'}, name='play-productions-past'),
    path('play/<b32:play_id>/<slug:play>/edit', plays.play_edit, name='play-edit'),
    path('play/<b32:play_id>/<slug:play>/add', productions.add_from_play, name='play-production-add'),
    path('play/<b32:play_id>/<slug:play>', plays.play, name='play'),
    path('play/<b32:play_id>', plays.play_short_url),

    # url('^play/(?P<play>.*?)/part/(?P<part>.*)$', productions.by_part),

    path('people', people.PersonList.as_view(), name='people_all'),
    path('people/<letter:letter>', people.PersonList.as_view(), name='people'),
    path('person/<b32:person_id>/<emptyslug:person>/future', people.person_productions, {'type': 'future'}, name='person-productions-future'),
    path('person/<b32:person_id>/<emptyslug:person>/past', people.person_productions, {'type': 'past'}, name='person-productions-past'),
    path('person/<b32:person_id>/<emptyslug:person>/edit', people.person_edit, name='person-edit'),
    path('person/<b32:person_id>/<emptyslug:person>.js', people.person_js, name='person-json'),
    path('person/<b32:person_id>/<emptyslug:person>', people.person, name='person'),
    path('person/<b32:person_id>', people.person_short_url),

    path('places', places.PlaceList.as_view(), name='places_all'),
    path('places/<letter:letter>', places.PlaceList.as_view(), name='places'),
    path('place/<b32:place_id>/<slug:place>/future', places.place_productions, {'type': 'future'}, name='place-productions-future'),
    path('place/<b32:place_id>/<slug:place>/past', places.place_productions, {'type': 'past'}, name='place-productions-past'),
    path('place/<b32:place_id>/<slug:place>/edit', places.place_edit, name='place-edit'),
    path('place/<b32:place_id>/<slug:place>/add', productions.add_from_place, name='place-production-add'),
    path('place/<b32:place_id>/<slug:place>/productions', places.productions, name='place-productions'),
    path('place/<b32:place_id>/<slug:place>/people', places.people, name='place-people'),
    path('place/<b32:place_id>/<slug:place>', places.place, name='place'),
    path('place/<b32:place_id>', places.place_short_url),

    path('company/<b32:company_id>/<emptyslug:company>/future', productions.company_productions, {'type': 'future'}, name='company-productions-future'),
    path('company/<b32:company_id>/<emptyslug:company>/past', productions.company_productions, {'type': 'past'}, name='company-productions-past'),
    path('company/<b32:company_id>/<emptyslug:company>/edit', productions.company_edit, name='company-edit'),
    path('company/<b32:company_id>/<emptyslug:company>/add', productions.add_from_company, name='company-production-add'),
    path('company/<b32:company_id>/<emptyslug:company>', productions.company, name='company'),
    path('company/<b32:company_id>', productions.production_company_short_url),

    path('observations/post/', productions.post_comment_wrapper),
    path('observations/remove/<int:comment_id>', productions.hide_comment, name='hide-comment'),
    path('observations/', include('django_comments.urls')),
    path('photograph/take/', photos.take_photo, name='take-photo'),
    path('photograph/taken/', photos.photo_taken, name='photo-taken'),
    path('photograph/view/<slug:photo_id>', photos.view, name='photo-view'),

    path('search/around/<path:s>/future', search.search_around, {'type': 'future'}, name='search-around-future'),
    path('search/around/<path:s>/past', search.search_around, {'type': 'past'}, name='search-around-past'),
    path('search/around/<path:s>', search.search_around, name='search-around'),
    path('search/parts/<path:search>', search.search_parts, name='search-parts'),
    path('search', search.search, name='search'),

    path('ajax/autocomplete', search.search_autocomplete, name='search-autocomplete'),

    path('add', productions.production_add, name='production-add'),

    path('profile/edit', profiles.profile_edit, name='profile-edit'),
    path('profile/<slug:username>', profiles.profile, name='profile'),
    path('profile', profiles.profile_user, name='profile-user'),

    path('publicity/feed', NewsFeed()),
    path('publicity', news.NewsIndex.as_view(), name='news-index'),
    path('publicity/<int:year>', news.NewsYear.as_view(), name='news-year'),
    path('publicity/<int:year>/<slug:month>', news.NewsMonth.as_view(), name='news-month'),
    path('publicity/<int:year>/<slug:month>/<slug:slug>',
         news.NewsArticle.as_view(), name='news-entry'),

    path('random', views.random_production, name='random'),
    # url('forums/forum/', include('forums.django-forum.forum.urls')),
    # url('forums/simple/', include('forums.django-simpleforum.forum.urls')),
    # url('forums/bb/', include('forums.djangobb.djangobb.urls')),

news/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class ArticleManager(models.Manager):
    def visible(self):
        return super(ArticleManager, self).get_queryset().filter(visible=True)


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    enable_comments = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique_for_month='created')
    title = models.CharField(max_length=100)
    visible = models.BooleanField(default=False)
    body = models.TextField()
    body_html = models.TextField(editable=False, blank=True)

    objects = ArticleManager()

    class Meta:
        get_latest_by = 'created'
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        super(Article, self).save(kwargs)

    def get_absolute_url(self):
        return reverse('news-entry', kwargs={
            'year': self.created.year,
            'month': self.created.strftime('%B').lower(),
            'slug': self.slug,
        })

    def get_next(self):
        return self.get_next_by_pub_date(visible=True)

    def get_previous(self):
        return self.get_previous_by_pub_date(visible=True)

places/models.py
import re
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.template.defaultfilters import slugify
from django.urls import reverse
from photos.models import Photo
from utils import int_to_base32, base32_to_int, pretty_date_range
from fields import ApproximateDateField
from common.models import Alert
from countries.models import Country


class PlaceManager(models.Manager):
    # Crappy bounding box, need to do radial!
    def around(self, lat, lon):
        return self.get_queryset().filter(
            longitude__gte=lon - 0.1,
            longitude__lte=lon + 0.1,
            latitude__gte=lat - 0.1,
            latitude__lte=lat + 0.1
        )

    def get(self, **kwargs):
        b32 = kwargs.pop('Bid', None)
        if b32:
            kwargs['id'] = base32_to_int(b32)
        return super(PlaceManager, self).get(**kwargs)


class Place(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.PROTECT, related_name='children')
    slug = models.SlugField(max_length=150)
    description = models.TextField(blank=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    address = models.CharField(blank=True, max_length=200)
    town = models.CharField(blank=True, max_length=50)
    country = models.ForeignKey(Country, blank=True, null=True, on_delete=models.SET_NULL)
    postcode = models.CharField(blank=True, max_length=10)
    telephone = models.CharField(blank=True, max_length=50)
    type = models.CharField(
        blank=True, max_length=100, choices=(
            ('proscenium', 'Proscenium Arch'),
            ('thrust', 'Thrust'),
            ('multiple', 'Multiple'),
            ('other', 'Other')
        )
    )
    size = models.CharField('Seats', blank=True, max_length=100)
    opening_date = ApproximateDateField(blank=True)
    closing_date = ApproximateDateField(blank=True, default='')
    url = models.URLField('URL', blank=True)
    wikipedia = models.URLField(blank=True)
    photos = GenericRelation(Photo)

    objects = PlaceManager()

    alerts = GenericRelation(Alert)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self._str_with_name()

    def save(self, **kwargs):
        name = re.sub('(?i)^(.*), (A|An|The)$', r'\2 \1', self.name.strip())
        include_town = kwargs.pop('include_town', None)
        m = re.match('(.*), ([^,]*)$', name)
        if include_town and m:
            self.name = name = m.group(1)
            self.town = m.group(2)
        self.slug = slugify('%s %s' % (name, self.town))
        self.name = re.sub('(?i)^(A|An|The) (.*)$', r'\2, \1', self.name.strip())
        super(Place, self).save(**kwargs)

    def get_name_display(self):
        out = self.name
        m = re.search(r'(?i)^(.*),\s+(A|An|The)$', out)
        if m:
            out = "%s %s" % (m.group(2), m.group(1))
        return out

    def _str_with_name(self, name=None):
        out = name if name else self.get_name_display()
        if self.parent:
            out = '%s, %s' % (out, self.parent.get_name_display())
        if self.town and self.town not in out:
            out += ", " + self.town
        return out

    def name_for_date(self, date):
        if not date:
            return self._str_with_name()
        name = self.other_names.filter(start_date__lte=date, end_date__gte=date).first()
        if name:
            name = '%s (now %s)' % (name.get_name_display(), self.get_name_display())
        return self._str_with_name(name)

    @property
    def id32(self):
        return int_to_base32(self.id)

    def make_url(self, name, *args):
        return reverse(name, args=(self.id32, self.slug) + args)

    def get_absolute_url(self):
        return self.make_url('place')

    def get_edit_url(self):
        return self.make_url('place-edit')

    def get_add_production_url(self):
        return self.make_url('place-production-add')

    def get_past_url(self):
        return '%s/past' % self.get_absolute_url()

    def get_future_url(self):
        return '%s/future' % self.get_absolute_url()

    def get_feed_url(self):
        return '%s/feed' % self.get_absolute_url()

    def get_productions_url(self):
        return self.make_url('place-productions')


class Name(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE, related_name='other_names')
    name = models.CharField(max_length=100)
    start_date = ApproximateDateField(blank=True)
    end_date = ApproximateDateField(blank=True)

    class Meta:
        ordering = ['-end_date', '-start_date', 'name']

    def __str__(self):
        out = self.get_name_display()
        if self.place.town and self.place.town not in out:
            out += f", {self.place.town}"
        date_range = pretty_date_range(self.start_date, None, self.end_date)
        out += f' ({date_range})'
        return out

    def save(self, **kwargs):
        self.name = re.sub('(?i)^(A|An|The) (.*)$', r'\2, \1', self.name.strip())
        super(Name, self).save(**kwargs)

    def get_name_display(self):
        out = self.name
        m = re.search(r'(?i)^(.*),\s+(A|An|The)$', out)
        if m:
            out = "%s %s" % (m.group(2), m.group(1))
        return out

    def get_absolute_url(self):
        return self.place.get_absolute_url()


def first_letters():
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute('SELECT DISTINCT SUBSTRING(name, 1, 1) FROM places_place')
    return cursor.fetchall()

search/models.py
# Create your models here.

search/forms.py
from django import forms
# from fields import ApproximateDateFormField


class SearchForm(forms.Form):
    play = forms.CharField(required=False)
    person = forms.CharField(required=False)
    place = forms.CharField(required=False)
    # date = ApproximateDateFormField()
    # role = forms.CharField()

templates/contact.html
{% extends "base.html" %}

{% block title %}Criticism{% endblock %}

{% block content %}

<h1>Criticism</h1>

<blockquote class="verse"><pre>
1. The action of criticizing, or passing judgement upon the qualities or merits of anything
2. The art of estimating the qualities and character of literary or artistic work;
   the function or work of a critic.
</pre></blockquote>

<p>This site is run as a hobby;
constructive positive criticism or other contact is welcome &ndash; especially
if you&rsquo;re from a theatre with a large archive you want to include
on the site! :-)

<p>Please note that all the information I have is on the site – I don’t have
any further information on a particular production or person that I could give
you. If you have an observation about a production, or a photograph concerning
something on the site, please do add it to the site directly, thank you.</p>

<style>
span#aatt span { display: none; }
span#aatt::before { content: "@"; }
</style>
<p>You can see or make
<a href="https://github.com/dracos/Theatricalia/issues">feature
requests and bug reports at GitHub</a>, or &#101;mail me at
principal<span id="aatt"><span>-at-</span></span>theatricalia.com.

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load prettify %}
{% load thumbnail %}

{% block extra_head %}
<link href="/publicity/feed" type="application/rss+xml" rel="alternate">
{% endblock %}

{% block fulltitle %}Theatricalia{% endblock %}

{% block extra_body %} id="home"{% endblock %}

{% block content %}

<div class="col" id="features">

<p id="hello">Hello and welcome to Theatricalia, a <strong>database</strong> of past
and future <strong>theatre productions</strong>.

<h2 class="no-descenders">Features</h2>

<ul>
<li>Anyone can <a href="/add" title="Add a production">add a production</a>
if it&rsquo;s not on the site, or fix mistakes.
<li>Search for a person, play, place, or part;
or search for a location to find things near you.
</ul>

</div>

<div class="col" id="status">

<p>Theatricalia knows about
<strong>{{ people|prettify_num }}</strong> people being cast and crew in
<strong>{{ parts|prettify_num }}</strong> r&ocirc;les, in
<strong>{{ productions|prettify_num }}</strong> productions of
<strong>{{ plays|prettify_num }}</strong> plays at
<strong>{{ places|prettify_num }}</strong> places.
</p>

<h2>For example&hellip;</h2>

{% if random_photo %}

{% with random_photo.0.content_object as production %}
    {% thumbnail random_photo.0.photo "108x108" crop="center" as im %}
<p><img align="right" src="{{ im.url }}" width={{ im.width }} height={{ im.height }} alt="" style="margin-left:0.5em">
<a href="{{ production.play.get_absolute_url }}">{{ production.play.get_title_display|prettify }}</a>{% if production.get_companies_display %}
by {{ production.get_companies_display }}{% endif %},
    {% endthumbnail %}

{% if production.places.count == 1 %}
    {{ production.date_summary|prettify }},
    at <a href="{{ production.places.all.0.get_absolute_url }}">{{ production.places.all.0.get_name_display|prettify }}</a>.</p>
{% else %}
    {% if production.places.count == 0 %}
                at an unknown location.
    {% else %}
                       at
        {% for place in production.place_set.all %}
            {% if forloop.last and not forloop.first %} and {% endif %}
            <a href="{{ place.place.get_absolute_url }}">{{ place.place.get_name_display|prettify }}</a>
            <small>({{ place.date_summary|prettify }})</small>{% if forloop.revcounter0 == 0 %}{% elif forloop.revcounter0 == 1 %}{% if forloop.counter0 != 0 %},{% endif %}{% else %},{% endif %}{% endfor %}.
    {% endif %}
{% endif %}

<p align="right"><a href="{{ production.get_absolute_url }}">More &rarr;</a></p>

{% endwith %}

{% else %}

<p><img align="right" width=115 height=155 src="/static/i/hamlet.jpg" alt="" style="margin-left:0.5em">
<a href="/person/7xk/david-tennant">David Tennant</a>
played the title role in the
<a href="/play/2/hamlet/production/3qn">Royal Shakespeare Company&rsquo;s production</a>
of <a href="/play/2/hamlet">Hamlet</a> by
<a href="/person/1/william-shakespeare">William Shakespeare</a>
at the <a href="/place/46/courtyard-theatre-stratford-upon-avon">Courtyard Theatre</a>.
<p>David also appeared in a
<a href="/play/3/as-you-like-it/production/2y8">production of As You Like It</a>, alongside
<a href="/person/7rg/colin-farrell">Colin Farrell</a> and
<a href="/person/7sm/joseph-fiennes">Joseph Fiennes</a>.

{% endif %}

</div>

<div id="latest" class="col">

<!--
<h2 class="no-descenders">Site news</h2>

{% if latest_news %}
    <p><strong>{{ latest_news.title }}:</strong>
    {{ latest_news.body|safe|truncatewords:"20"|prettify }}
    <a href="{{ latest_news.get_absolute_url }}">More &rarr;</a>
{% else %}
    <p>No news yet, we haven&rsquo;t launched!</p>
{% endif %}
-->

<h2 class="no-descenders">Most recent&hellip;</h2>

<ul>
<li><strong>&hellip;addition:</strong>
{% if latest_production %}
<a href="{{ latest_production.get_absolute_url }}">{{ latest_production.play.get_title_display|prettify }}</a>,
{% if latest_production.places.count == 1 %}
    at <a href="{{ latest_production.places.all.0.get_absolute_url }}">{{ latest_production.places.all.0|prettify }}</a>,
    {{ latest_production.date_summary|prettify }}.
    {% if latest_production.place_set.all.0.press_date and latest_production.place_set.all.0.start_date %}
        Press night was {{ latest_production.place_set.all.0.press_date|date:"jS F Y"|prettify }}.
    {% endif %}
{% elif latest_production.places.count == 0 %}
    at an unknown location.
{% else %}
    {% firstof latest_production.place_set_ordered|length as places %}
    at
    {% for place in latest_production.place_set_ordered|slice:":5" %}
        {% if forloop.last and not forloop.first and places|add:0 <= 5 %} and {% endif %}
        <a href="{{ place.place.get_absolute_url }}">{{ place.place|prettify }}</a>
        <small>({{ place.date_summary|prettify }})</small>{% if forloop.revcounter0 == 0 %}{% elif forloop.revcounter0 == 1 %}{% if forloop.counter0 != 0 %},{% endif %}{% else %},{% endif %}{% endfor %}{% if places|add:0 > 5 %} and other locations{% endif %}.
{% endif %}
{% if latest_production.last_modifier != latest_production.creator %}
Added by <a href="{{ latest_production.creator.profile.get_absolute_url }}">{{ latest_production.creator.name }}</a>, last modified by <a href="{{ latest_production.last_modifier.profile.get_absolute_url }}">{{ latest_production.last_modifier.name }}</a>.
{% elif latest_production.creator.name %}
Added by <a href="{{ latest_production.creator.profile.get_absolute_url }}">{{ latest_production.creator.name }}</a>.
{% endif %}
{% else %}
Nothing in the system yet!
{% endif %}

<li><p><strong>&hellip;observation:</strong>

{% if latest_observation %}
On {{ latest_observation.submit_date|date:"jS F Y"|prettify }}
at {{ latest_observation.submit_date|date:"g:i a" }},
<a href="{{ latest_observation.user.profile.get_absolute_url }}">{{ latest_observation.user_name|prettify }}</a> noted,
about a <a href="{{ latest_observation.content_object.get_absolute_url }}">production</a> of {{ latest_observation.content_object.play.get_title_display|prettify }}:</p>
<blockquote><p>{{ latest_observation.comment|truncatewords:10|prettify }}
<a href="{{ latest_observation.content_object.get_absolute_url }}#o{{ latest_observation.id }}">More &rarr;</a>
</p></blockquote>
{% else %}
Nothing in the system yet!</p>
{% endif %}

</ul>

</div>

<div id="warning">
<p><em>Please be aware that no photography or recording equipment is allowed,
and no food or drink is to be consumed, within the theatre.
Please turn off all mobile telephones and other devices that may sound,
as these distract not only the audience, but also the performers.</em>
Thank you.</p>
</div>

<a style="display:none" rel="me" href="https://mastodon.social/@dracos">Me on Mastodon</a>

{% endblock %}

templates/read_only.html
{% extends "base.html" %}

{% block title %}Transfer{% endblock %}

{% block content %}

<h1>Transfer</h1>

<p>Not to the west end or Broadway, but as we
are currently moving servers, everything is read
only so we do not lose anything.

{% endblock %}

templates/search-around-productions.html
{% extends 'base.html' %}
{% load prettify %}

{% block title %}Search around ({{ lat }}, {{ lon }}){% endblock %}

{% block extra_head %}
<script type="text/javascript" src="/static/js/web-maps-lite.js"></script>
{% endblock %}

{% block content %}

<h1>Search</h1>

<div class="primary">

{% if page_obj.object_list %}
<h2>{{ type }}</h2>
<ul class="production_list">
{% for production in page_obj.object_list %}
<li><a href="{{ production.get_absolute_url }}">{{ production.play.get_title_display|prettify }}</a>{% if production.get_companies_display %}, {{ production.get_companies_display }}{% endif %}
<span class="meta">{{ production.date_summary|prettify }},
{% if production.places.count == 1 %}
<a href="{{ production.places.all.0.get_absolute_url }}">{{ production.place_summary|prettify }}</a>.
{% else %}
{{ production.place_summary|prettify }}.
{% endif %}
</span>
{% endfor %}
</ul>
{% endif %}

</div>

<div class="secondary">
<p>{{ type }} around the location ({{ lat }}, {{ lon }}).</p>

{% include 'pagination.html' %}
</div>

{% endblock %}

templates/search-parts.html
{% extends 'base.html' %}
{% load prettify %}

{% block title %}Search{% if search %}: &ldquo;{{ search|striptags }}&rdquo;{% endif %}{% endblock %}

{% block content %}

<h1>Search{% if object %} for &ldquo;{{ object }}&rdquo;{% endif %}</h1>

{% if page_obj.object_list %}
<h2>Parts</h2>
<div class="primary">

<ul class="production_list">
{% for part in page_obj.object_list %}
<li>
{{ part.role|prettify }}, played by <a href="{{ part.person.get_absolute_url }}">{{ part.person|prettify }}</a>, in
<a href="{{ part.production.get_absolute_url }}">{{ part.production.play.get_title_display|prettify }}</a>{% if part.production.get_companies_display %}, {{ part.production.get_companies_display }}{% endif %}
<span class="meta">{{ part.production.date_summary|prettify }},
{% if part.production.places.count == 1 %}
<a href="{{ part.production.places.all.0.get_absolute_url }}">{{ part.production.place_summary|prettify }}</a>.
{% else %}
{{ part.production.place_summary|prettify }}.
{% endif %}
</span>
{% endfor %}
</ul>
{% else %}
<p>There are no results to display.</p>
{% endif %}

{% include "pagination.html" %}

</div>

<div class="secondary">
{% include "pagination.html" %}
</div>

{% endblock %}